apiVersion: v1
kind: DeploymentConfig
metadata:
  name: helloworld
  namespace: 3scale
  selfLink: /oapi/v1/namespaces/3scale/deploymentconfigs/helloworld
  labels:
    app: helloworld
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - helloworld
        from:
          kind: ImageStreamTag
          namespace: 3scale
          name: 'helloworld:latest'
  replicas: 2
  selector:
    app: helloworld
    deploymentconfig: helloworld
  template:
    metadata:
      labels:
        app: helloworld
        deploymentconfig: helloworld
    spec:
      containers:
        - name: helloworld
          image: '172.30.47.227:5000/3scale/helloworld'
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: '6379'
          resources:
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
