apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: 3scale
  selfLink: /api/v1/namespaces/3scale/services/helloworld
  labels:
    app: helloworld
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    deploymentconfig: helloworld
  type: ClusterIP
  sessionAffinity: None
